### ISSUE TITLE
Dataset question

### ISSUE THREAD

**Issue by steplee** [JirongZhang/DeepHomography#13]
Besides taking the video frames as described in the paper, did you also warp one of the pair along the lines of DeTone? Otherwise the generalization on heavily skewed pairs is surprising, considering videos never seem to have that much distortion.

**Comment by JirongZhang** [comment]
Nice question. Detone's contribution lies in the novel method of homography estimation. But model trained from synthetic image pairs can't estimate an accurate homography between two images from real world. At present, our approach cannot solve the case of very large distortion. @steplee
