### ISSUE TITLE
Hope you public the code soon.

### ISSUE THREAD

**Issue by leeskyed** [JirongZhang/DeepHomography#15]
Congratulations! I saw your paper has been accepted by ECCV 2020. Hope you public the code soon.

**Comment by lhaippp** [comment]
maybe in one week

**Comment by leeskyed** [comment]
@lhaippp well, it's almost a week now. When will it be updated?

**Comment by JirongZhang** [comment]
> Congratulations! I saw your paper has been accepted by ECCV 2020. Hope you public the code soon.

Sorry for waiting and very thanks for your following. The new version of paper adds a lot of discussion. Our codes\dataset link\final version of paper\page will be updated soon. We're speeding up and we've done most of it. thanks again.

**Comment by waicool20** [comment]
@JirongZhang Any updates on this?

**Comment by leeskyed** [comment]
@JirongZhang any updates?

**Comment by JirongZhang** [comment]
Sorry for waiting and very thanks for your following, we have updated the repository. @waicool20 @leeskyed
