### ISSUE TITLE
Some questions of the labeled points

### ISSUE THREAD

**Issue by BrightHammer** [JirongZhang/DeepHomography#44]
I visualized the labeled points of the test data. It is confusing that most of the labeled points are located in regions lacking texture or with small gradients. Both 'Coordinate' and the updated 'Coordinate-v2' have similar characteristics.

What are the main factors that the authors consider when selecting or annotating the labeled points?
How does the current annotation ensure the accuracy?
In other words, if a more obvious location is selected as the key point, will there be higher annotation accuracy?

![00002](https://user-images.githubusercontent.com/38350205/207524517-70eb9c87-a613-4b51-8411-d6a3baa9a971.jpg)
![00006](https://user-images.githubusercontent.com/38350205/207524516-aa7b22d2-3ba1-4c27-9be7-36411bfafd9f.jpg)

**Comment by lhaippp** [comment]
I think the visualization size(image size) is not correct, i.e., the image should be resized to certain size.
In my mind, you could findthe image size in testdataset.

**Comment by BrightHammer** [comment]
> I think the visualization size(image size) is not correct, i.e., the image should be resized to certain size. In my mind, you could findthe image size in testdataset.

You’re right, I wasn’t careful enough before. The pictures looked much better after I resized it to (640,360).
![00002-v2](https://user-images.githubusercontent.com/38350205/227781733-3a763512-8353-48de-985a-9c1d0aeddf9b.jpg)
![00006-v2](https://user-images.githubusercontent.com/38350205/227781744-0be14636-a49d-4673-91d3-24583ce8b2e9.jpg)
