### ISSUE TITLE
Calculate homography matrix problem 

### ISSUE THREAD

**Issue by tomjerrygithub** [JirongZhang/DeepHomography#5]
outputs = Mode(input)
outputs.shape   is   (4,2)
because the outputs is the  offsets, so  i  need to do  like this ：
h, status = cv2.findHomography(np.add(orf,outputs),orf)

when i calculate the loss ,what is the  orf (source points )？

**Comment by JirongZhang** [comment]
All processes need to be implemented with torch or tf, so that the entire calculation process is differentiable. You can refer to this paper(https://arxiv.org/abs/1709.03966) and its code for the process of 'Warp' with STN.

**Comment by JirongZhang** [comment]
All processes need to be implemented with torch or tf, so that the entire calculation process is differentiable. You can refer to this paper(https://arxiv.org/abs/1709.03966) and its code for the process of 'Warp' with STN.
