### ISSUE TITLE
BEBLID

### ISSUE THREAD

**Issue by DoongLi** [JirongZhang/DeepHomography#52]
![1710072688751](https://github.com/JirongZhang/DeepHomography/assets/86915071/5afcbe89-222f-4a99-9e43-11a882c446b1)

Hi, I saw the papers compared to BEBLID, but Beblid is just a descriptor method, so what do you use for the corner point of this option?

**Comment by CallMeFrozenBanana** [comment]
Hi~ It can be used via the points detector of ORB  (FAST)

**Comment by DoongLi** [comment]
Ok, thx~
