### ISSUE TITLE
 Is the loss function in the code not as comprehensive compared to the loss function described in the paper?

### ISSUE THREAD

**Issue by Jerry-bear** [JirongZhang/DeepHomography#53]
I currently have a question regarding the loss function calculation in my code. It seems that only the L1 loss has been calculated, but the loss in the paper is described as follows. Could you tell me if I need to add the feature_loss, l1_loss, and smooth_loss together with specific weights?

> > > It seems that your input points (h4p/h4p1/h4p2) number are half of needed
> > 
> > 
> > Should each batchsize(h4p/h4p1/h4p2)have (divide +1) * (divide +1) * 2*2 points, and why?
> 
> sorry the "The input for h4p is [bs, 4]" confused me。 But it's "[bs, 8]" in your description later, which is the correct size. Come on, the correct size should always be (divide +1) * (divide +1) * 2.

I currently have a question regarding the loss function calculation in my code. It seems that only the
![image](https://github.com/JirongZhang/DeepHomography/assets/55934441/f79abdf3-279b-4a44-9e83-93b2b167733c)
has been calculated, but the loss in the paper is described as follows.
![image](https://github.com/JirongZhang/DeepHomography/assets/55934441/04fe9269-dd01-48bf-9a96-b1771977d4b1)
 Could you tell me if I need to add the feature_loss, l1_loss, and smooth_loss together with specific weights?And also, does the content within the following red area not yet reflected in the network?
![image](https://github.com/JirongZhang/DeepHomography/assets/55934441/ec52dfe3-3ae5-4f8f-adfa-bef8bcf3e541)

_Originally posted by @Jerry-bear in https://github.com/JirongZhang/DeepHomography/issues/51#issuecomment-1987563638_

**Comment by Jerry-bear** [comment]
After reviewing previous issues, I now understand that the code implements an Oneline mode, whereas the paper mentions a Doubleline mode. If I want to switch to the Doubleline mode, do I need to manually write the missing loss functions?

**Comment by CallMeFrozenBanana** [comment]
Hi ~ This is a regularization term in the Doubleline mode, but I don't think it is essential

**Comment by Jerry-bear** [comment]
> Hi ~ This is a regularization term in the Doubleline mode, but I don't think it is essential


So, I just need to subtract the L1 loss from the original loss, right?
