### ISSUE TITLE
How to use the 128*128 model to bigger image

### ISSUE THREAD

**Issue by tomjerrygithub** [JirongZhang/DeepHomography#8]
hi ，i had trained a model with 128128
than i want to use this model to 19201080
i croped 128128 from 19201080 than estimate a H；
but has tow problems：
a、transform the 19201080 and crop the same place 128128 looks good，but the whole image is worse
b、i choose different 128*128 area to predict get very different H。

what should i to to use this model in my project ？

**Comment by leeskyed** [comment]
Hello, did you model works? Would you mind providing the code of the loss function? We found that didn't work well.

**Comment by JirongZhang** [comment]
Sorry for waiting and very thanks for your following, we have updated the repository. Please try again.
